server:
  http2:
    enabled: true
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  application:
    name: "@project.name@"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    add-properties: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    rest:
      detection-strategy: annotated
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      encoding: UTF-8

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs