server:
  http2:
    enabled: true
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  application:
    name: "@project.name@"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    add-properties: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

client:
  pokemon:
    url: https://pokeapi.co/api
    endpoint:
      evolution-chain: /v2/evolution-chain/1
